module.exports = [
  // ======== DINAS AKADEMIK ======== //
  {
    nama: "WANDA HAMIDAH",
    nim: "09011282227052",
    lulus: true,
    dinas: "Akademik",
    divisi: "",
  },
  {
    nama: "SITI LATIFAH",
    nim: "09011182227001",
    lulus: true,
    dinas: "Akademik",
    divisi: "",
  },
  {
    nama: "MARSELLA VINDRIANI",
    nim: "09011282227094",
    lulus: true,
    dinas: "Akademik",
    divisi: "",
  },
  {
    nama: "RIZKI MEIDA SARI",
    nim: "09011282227067",
    lulus: true,
    dinas: "Akademik",
    divisi: "",
  },
  {
    nama: "CANTIKA NAFISA ROYYANI",
    nim: "09011182227022",
    lulus: true,
    dinas: "Akademik",
    divisi: "",
  },
  {
    nama: "ZAHRA MAHARANI PUTRI",
    nim: "09011282227105",
    lulus: true,
    dinas: "Akademik",
    divisi: "",
  },
  // ======== DINAS PSDM ======== //
  {
    nama: "FELIANA YUNITA",
    nim: "09011282227039",
    lulus: true,
    dinas: "Pengembangan Sumber Daya Manusia (PSDM)",
    divisi: "",
  },
  {
    nama: "RAKA MANGGALA PUTRA REKSA",
    nim: "09011282227034",
    lulus: true,
    dinas: "Pengembangan Sumber Daya Manusia (PSDM)",
    divisi: "",
  },
  {
    nama: "MUHAMMAD SANDU PASWALLAH",
    nim: "09011282227041",
    lulus: true,
    dinas: "Pengembangan Sumber Daya Manusia (PSDM)",
    divisi: "",
  },
  {
    nama: "DHANI SAPUTRA",
    nim: "09011182126019",
    lulus: true,
    dinas: "Pengembangan Sumber Daya Manusia (PSDM)",
    divisi: "",
  },
  {
    nama: "MUHAMMAD REXIE FERNANDO",
    nim: "09011282227106",
    lulus: true,
    dinas: "Pengembangan Sumber Daya Manusia (PSDM)",
    divisi: "",
  },
  {
    nama: "ANDESA PUTRA GB",
    nim: "09011382227147",
    lulus: true,
    dinas: "Pengembangan Sumber Daya Manusia (PSDM)",
    divisi: "",
  },
  {
    nama: "NANDA AUSIL JANNATI",
    nim: "09011282227096",
    lulus: true,
    dinas: "Pengembangan Sumber Daya Manusia (PSDM)",
    divisi: "",
  },
  // ======== DINAS PMB ======== //
  {
    nama: "BERTI AYUZAHARA",
    nim: "09011182227120",
    lulus: true,
    dinas: "Pengembangan Minat dan Bakat (PMB)",
    divisi: "Seni",
  },
  {
    nama: "ARYADIKA",
    nim: "09011382227132",
    lulus: true,
    dinas: "Pengembangan Minat dan Bakat (PMB)",
    divisi: "Olahraga",
  },
  {
    nama: "M. RAFLI YANDA FADZIL GUMAY",
    nim: "09011282126097",
    lulus: true,
    dinas: "Pengembangan Minat dan Bakat (PMB)",
    divisi: "Olahraga",
  },
  {
    nama: "GARINDIYO RIFKI TRIMAHENTA P.",
    nim: "09011282126071",
    lulus: true,
    dinas: "Pengembangan Minat dan Bakat (PMB)",
    divisi: "Olahraga",
  },
  {
    nama: "BELIANA CAHAYA PRISKA",
    nim: "09011282227061",
    lulus: true,
    dinas: "Pengembangan Minat dan Bakat (PMB)",
    divisi: "Olahraga",
  },
  {
    nama: "TIARA PUTRI AMANDA",
    nim: "09011182227015",
    lulus: true,
    dinas: "Pengembangan Minat dan Bakat (PMB)",
    divisi: "",
  },
  {
    nama: "PRATAMA ARJAN RANGKUTI",
    nim: "09011182227006",
    lulus: true,
    dinas: "Pengembangan Minat dan Bakat (PMB)",
    divisi: "Seni",
  },
  {
    nama: "FAKHRI NAUFAL DHAIFULLAH",
    nim: "09011282227108",
    lulus: true,
    dinas: "Pengembangan Minat dan Bakat (PMB)",
    divisi: "Seni",
  },
  // ======== DINAS DANUS ======== //
  {
    nama: "MIRDZA QOMARUL JAYA",
    nim: "09011282227110",
    lulus: true,
    dinas: "Dana dan Usaha (Danus)",
    divisi: "",
  },
  {
    nama: "PRAWIRANGGA CAESAR NAGEF PUTRA BALADEWA",
    nim: "09011282227070",
    lulus: true,
    dinas: "Dana dan Usaha (Danus)",
    divisi: "",
  },
  {
    nama: "IKA PUTRI APRILIA",
    nim: "09011182227020",
    lulus: true,
    dinas: "Dana dan Usaha (Danus)",
    divisi: "",
  },

  {
    nama: "AULYA PUTRI AYU",
    nim: "09011182227118",
    lulus: true,
    dinas: "Dana dan Usaha (Danus)",
    divisi: "",
  },
  // ======== DINAS KASTRAD ======== //
  {
    nama: "FALKI ANUGRAH AKBAR",
    nim: "09011282227112",
    lulus: true,
    dinas: "Kajian Strategi dan Advokasi (Kastrad)",
    divisi: "",
  },
  {
    nama: "NURAINIYAH SOLEHAN",
    nim: "09011282227092",
    lulus: true,
    dinas: "Kajian Strategi dan Advokasi (Kastrad)",
    divisi: "",
  },
  {
    nama: "M. AKBAR SAPUTRA",
    nim: "09011282227088",
    lulus: true,
    dinas: "Kajian Strategi dan Advokasi (Kastrad)",
    divisi: "",
  },
  {
    nama: "MUHAMMAD RABBEL AKHIRUL",
    nim: "09011182227002",
    lulus: true,
    dinas: "Kajian Strategi dan Advokasi (Kastrad)",
    divisi: "",
  },
  {
    nama: "ISBATUDINIA",
    nim: "09011182227008",
    lulus: true,
    dinas: "Kajian Strategi dan Advokasi (Kastrad)",
    divisi: "",
  },
  // ======== DINAS INFOKOM ======== //
  {
    nama: "EKA RATNA ANINDITA",
    nim: "09011282227045",
    lulus: true,
    dinas: "Informasi dan Komunikasi (Infokom)",
    divisi: "Publikasi",
  },
  {
    nama: "FERY DWI DARMAWAN",
    nim: "09011282227032",
    lulus: true,
    dinas: "Informasi dan Komunikasi (Infokom)",
    divisi: "Multimedia",
  },
  {
    nama: "TASYA HARWANI BARUS",
    nim: "09011282227048",
    lulus: true,
    dinas: "Informasi dan Komunikasi (Infokom)",
    divisi: "Multimedia",
  },
  {
    nama: "MUHAMMAD RIZKI FEBRIAN",
    nim: "09011282227093",
    lulus: true,
    dinas: "Informasi dan Komunikasi (Infokom)",
    divisi: "Publikasi",
  },
  {
    nama: "DZHAHIRA SHAFA",
    nim: "09011382227150",
    lulus: true,
    dinas: "Informasi dan Komunikasi (Infokom)",
    divisi: "Multimedia",
  },
  {
    nama: "FAUZIAH RACHEL AUDREY CHELSEA",
    nim: "09011382227152",
    lulus: true,
    dinas: "Informasi dan Komunikasi (Infokom)",
    divisi: "Publikasi",
  },
  {
    nama: "FUAD ALMADILA MUHAMAD",
    nim: "09011282227030",
    lulus: true,
    dinas: "Informasi dan Komunikasi (Infokom)",
    divisi: "Multimedia",
  },
  {
    nama: "K. ADAM RIFKI AGUSTIAN",
    nim: "09011282227100",
    lulus: true,
    dinas: "Informasi dan Komunikasi (Infokom)",
    divisi: "Multimedia",
  },
  // ======== DINAS KESTARI ======== //
  {
    nama: "M. GAVIN HAWWARI",
    nim: "09011282227035",
    lulus: true,
    dinas: "Kesekretariatan (Kestari)",
    divisi: "",
  },
  {
    nama: "M. RAZHEL MIROZA",
    nim: "09011282227091",
    lulus: true,
    dinas: "Kesekretariatan (Kestari)",
    divisi: "",
  },
  {
    nama: "AULIA NASUHA",
    nim: "09011182227009",
    lulus: true,
    dinas: "Kesekretariatan (Kestari)",
    divisi: "",
  },
  {
    nama: "NUR RAMADHANI DWI PUTRI",
    nim: "09011282227069",
    lulus: true,
    dinas: "Kesekretariatan (Kestari)",
    divisi: "",
  },
];
